class BusinessConstants:

    DT_POR_CUTOFF = "18/09/1991"
    OC_CATEGORY = "OC_CATEGORY"
    BC_CATEGORY = "BC_CATEGORY"
    OC_OTHER_STATE = "OC_OTHER_STATE"
    MBC_DNC_CATEGORY = "MBC_DNC_CATEGORY"
    BCM_CATEGORY = "BCM_CATEGORY"
    SC_CATEGORY = "SC_CATEGORY"
    SCA_CATEGORY = "SCA_CATEGORY"
    ST_CATEGORY = "ST_CATEGORY"

    DIFF_ABLED = True
    MARKS_50_PER = 50
    MARKS_55_PER = 55

    MATCHED = 1
    NOT_MATCHED = 2

    SLET_STATUS = True
    NET_STATUS = True
